### ISSUE TITLE
Arpeggiator faceplate

### ISSUE THREAD

**Issue by lnikj** [jhoar/AmalgamatedHarmonics#2]
Just a quick note that the faceplate is short a few pixels top & bottom right and bottom. Cheers.

![jhoar_arpeggiator](https://user-images.githubusercontent.com/24451110/33239222-06acc284-d295-11e7-8aed-f5b6812d8e79.png)

**Comment by metaphorz** [comment]
Thanks for these 2 modules! I am trying to understand the Arpeggiator.  I assume that STEPS take something like LOG's DC offset to set the number of steps or does it take 0 to 1, or 0 to 5? Perhaps a tutorial vcv would help a lot if the documentation is not there.

**Comment by jhoar** [comment]
@metaphorz Yes, you're right, In the latest commit I've added what I hope are somewhat helpful notes which, in lieu of a proper tutorial, will have to do. I'm painfully aware that it needs some more UI elements to make it usable as a mix of guess work and dual attentuators to set things up is quite a pain.

So yes, it's just offsets to set up the steps.

The problem being is that my idea of what I think it should do and what I'm capable of implementing change from day to day, until it reaches the inevitable software singularity of being able to use it read email and surf.

**Comment by metaphorz** [comment]
This helps quite a bit, but I think I am completely lost. This may be because I am not yet familiar with modular vocabulary. For example:

1) You mention 6 pitches, but there are only 5 ports, so I assume you mean "5" in the README
2) When you say "P1 - P6: Input pitches", does that mean that P1..P5 are expecting DC values or audio signals? Are you expecting an integer like 440 or an output from a VCO?
3) Based on what you wrote for TRIG and CLOCK, would it be reasonable to have each of these to come from clocks, where one clock is N time as fast as the other? WIth N being the sequence number. If N=2, then you'd want what comes into CLOCK to be twice as fast as what goes into TRIG?
4) For STEP input, I am using the output of LOGInstruments's DC Offset. Since the output is floating point (like 2.04), are you rounding that value to determine the # of steps (2 in that
case) ?
5) the OUT would normally go into the Audio Driver?

**Comment by metaphorz** [comment]
I think I figured it out through output metering. It seems like P1...P5 are driven by a control signal that is [-5,5] in range? Then the output from the arp is another control voltage that can be fed into an oscillator. Here is example with Vessen as the wave function generator.
[ARPTest2.vcv.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1504646/ARPTest2.vcv.zip)

**Comment by jhoar** [comment]
Hi,
First - sorry - I did not mean to reply until I released the next version (which I have just done) so now the docs match the module. Not surprised you were confused.

1. Now there are 6 pitches...
2. DC values (i.e. -10V to 10V, 1 volt per octave - although only -5 to +5 is usable.
3. Yes, any clock source will do, I have been using a square wave LFO, but a clock with a clock divider is probably better
4. It's rounded down. I think.
5. OUT goes into the V/OCT input of a VCO (or whatever other sound generator that takes V/OCT input)

I attach the rack which I use to test things out:

[arp.vcv.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1505110/arp.vcv.zip)

The idle LFO in the bottom left can get hooked up to one of the IN of the dual attenuators supplying pitches.

**Comment by metaphorz** [comment]
Thanks - all of this is great. I downloaded your new patch. And I am attaching my revised patch based on your new module. To your points:

1. Thanks - I do wonder though whether a power of 2 would be more useful (e.g. 4 or 8)? I don't own a real modular so have no idea of how this is used in practice. however, for a seamless arpeggiation, having the clock ratio be 2,4, or 8 is easy and this depends on the number of frequencies (P1, P2, ..).  See how I have rigged this up in the attachment: there is the main clock signal (600BPM) and the /4 because there are four frequencies (P1, P2, P3, P4).

2. Got it on [-10,10]. I am guessing that OUT is also [-10,10] and GATE is [0,10]? I could barely hear anything above 5 so had assumed [-5,5] for P1,P2,...

3. OK.

4. That sounds like a "floor" operation. Eg.:  4.1 -> 4.0, 4.9 -> 4.0, 5.1 -> 5.0 and so on.

[ARPTest2.vcv.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1507101/ARPTest2.vcv.zip)

**Comment by jhoar** [comment]
1. Yes, I think that's a good option. I've opened an issue to track that.
2. Correct. Beyond [-5,5] on OUT is beyond my hearing range.
4. Right.

I'm going to close this issue now - thanks for your feedback on this, if there's anything else please opena new issue.
